# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jBkggS7sum16BWkreNUDL0e4Yv4n-f4n

->Experiment with 5 lists in-built function, and post it to github.
"""

lst=[2,4,6,8,"onkar","rishikesh","harshal",23.4,72.3,10,12,14,16]
lst

lst[5]

lst.append(18)
lst

lst.insert(6,"sai")
lst

lst.remove("harshal")
lst

lst.pop(6)
lst

lst.clear()
lst